project_id = "mfcnkltcdvitxczjwoer"

[functions.api-gateway]
verify_jwt = false

[functions.proxy-player]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.import-catalog]
verify_jwt = false

[functions.extract-video]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.smart-scraper]
verify_jwt = false

[functions.video-token]
verify_jwt = false

[functions.import-visioncine]
verify_jwt = false

[functions.push-notify]
verify_jwt = false

[functions.upload-r2]
verify_jwt = false

[functions.import-iptv]
verify_jwt = false

[functions.import-cineveo-catalog]
verify_jwt = false

[functions.import-json-catalog]
verify_jwt = false