project_id = "mfcnkltcdvitxczjwoer"

[functions.proxy-player]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.import-catalog]
verify_jwt = false

[functions.extract-video]
verify_jwt = false